# Site settings
title: Indra Kaw
description: "Meh."
baseurl: ""
url: "//indrakaw.github.io"

author: 
  name: "Indra Kurniawan"
  email: indrakaw@teknik.io
  skype_username: 
  twitter_username: 17zet
  github_username:  indrakaw
  steam_usermame: 
  quote: "Hi, I'm Indra Kurniawan."
  motto: "Never give-up!"

# Build settings
markdown: kramdown